version: '3'

services:
  app:
    build: 
        context: .
        dockerfile: ./docker/node/dockerfile
    ports:
      - '3000:3000'
      - '8080:8080'
    tty: true
    volumes:
      - ./src:/src
    working_dir: "/src"